
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/idealLibrary?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect